### ISSUE TITLE
rasterio-1.3.5 macosx_10_15_x86_64 wheels failing on import.

### ISSUE THREAD

**Issue by sharkinsspatial** [sgillies/rasterio-wheels#101]
On macOS 10.15.7 the following 
```
virtualenv venv
source venv/bin/activate
pip install rasterio==1.3.5 --no-cache-dir
```
```
python
>>> import rasterio
```
Returns
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/Downloads/rasterio_pytest/venv/lib/python3.9/site-packages/rasterio/__init__.py", line 28, in <module>
    from rasterio._version import gdal_version, get_geos_version, get_proj_version
ImportError: dlopen(/Users/user/Downloads/rasterio_pytest/venv/lib/python3.9/site-packages/rasterio/_version.cpython-39-darwin.so, 2): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Users/user/Downloads/rasterio_pytest/venv/lib/python3.9/site-packages/rasterio/.dylibs/libjxl.0.7.0.dylib (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib
```
In my tests both 
```
rasterio-1.3.5-cp38-cp38-macosx_10_15_x86_64.whl
rasterio-1.3.5-cp39-cp39-macosx_10_15_x86_64.whl
```
Are failing with the same error while
```
rasterio-1.3.4-cp38-cp38-macosx_10_15_x86_64.whl 
rasterio-1.3.4-cp39-cp39-macosx_10_15_x86_64.whl 
```
Work as expected

**Comment by sgillies** [comment]
@sharkinsspatial thanks for the report! I won't be able to do anything about this in tomorrow. Part of the problem is that GitHub upgraded their macos-latest runners between the 1.3.4 and 1.3.5 releases. The 1.3.4 wheels were built on macos-11 VMs and the 1.3.5 wheels on macos-12. Looks like I'll need to downgrade the instances from macos-latest and rebuild 1.3.5 wheels tomorrow.

**Comment by sgillies** [comment]
@sharkinsspatial 1.3.5.post1 wheels are on PyPI now. If they don't work, lemme know!
