### ISSUE TITLE
1.3.6 binary wheels   doesnt support GPKG, but 1.3.5 supports it

### ISSUE THREAD

**Issue by igieon** [sgillies/rasterio-wheels#105]
Steps to reproduce:
```
docker run --name python -it python:3.8-buster bash
```
```
pip install rasterio==1.3.5; python -c "import rasterio;print(rasterio.driver_from_extension('test.gpkg'))"
```
print GPKG, but
```
pip uninstall -y rasterio;pip install rasterio==1.3.6; python -c "import rasterio;print(rasterio.driver_from_extension('test.gpkg'))"
```
prints
```
returns error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/rasterio/drivers.py", line 71, in driver_from_extension
    return driver_extensions[os.path.splitext(path)[-1].lstrip(".").lower()]
KeyError: 'gpkg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/rasterio/drivers.py", line 73, in driver_from_extension
    raise ValueError("Unable to detect driver. Please specify driver.")
ValueError: Unable to detect driver. Please specify driver.
```

**Comment by sgillies** [comment]
Between 1.3.5 and 1.3.6, we switched over to GDAL's new Cmake builds and may have lost support for some formats (and gained others!) because the mapping from old to new build systems did not have 100% fidelity. @igieon are you saying that you used to be able to read/write GeoPackage rasters?

**Comment by igieon** [comment]
Yes i was able read GeoPackage. Now in all projects i use need to compile rasterio with gdal to have acccess to GeoPackage. 
I tested it now with rasterio 1.3.5 i am abble to read, but not with 1.3.6.

**Comment by sgillies** [comment]
Should be fixed now!
